<?php

namespace Tests\Unit;

use App\MainCategory;
use App\Status;
use App\Task;
use App\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Schema;
use Tests\TestCase;

class MainCategoryTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    private $task;
    private $mainCategory;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->mainCategory = factory(MainCategory::class)->create();
        $this->task = factory(Task::class)->create(['main_category_id' => $this->mainCategory->id]);
    }

    public function test_main_categories_database_has_expected_columns()
    {
        $this->assertTrue(
            Schema::hasColumns('main_categories', [
                'id', 'name'
            ])
        );
    }

    public function test_main_category_has_many_task()
    {
        $this->assertTrue($this->mainCategory->tasks->contains($this->task));
        $this->assertEquals(1, $this->mainCategory->tasks->count());
        $this->assertInstanceOf(Collection::class, $this->mainCategory->tasks);
    }
}
