<?php

namespace Tests\Unit;

use App\Status;
use App\Task;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Schema;
use Tests\TestCase;

class StatusTest extends TestCase
{
    use RefreshDatabase;

    private $task;
    private $status;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->status = factory(Status::class)->create();
        $this->task = factory(Task::class)->create(['status_id' => $this->status->id]);
    }

    public function test_statuses_database_has_expected_columns()
    {
        $this->assertTrue(
            Schema::hasColumns('statuses', [
                'id', 'name',
            ])
        );
    }

    public function test_status_has_many_task()
    {
        $this->assertTrue($this->status->tasks->contains($this->task));
        $this->assertEquals(1, $this->status->tasks->count());
        $this->assertInstanceOf(Collection::class, $this->status->tasks);
    }
}
